#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('FILESYSTEM_STDIO_EXPORTS', 1)
	conf.define('DONT_PROTECT_FILEIO_FUNCTIONS', 1)
	conf.define_cond('_USE_32BIT_TIME_T', conf.env.DEST_OS == 'win32')

def build(bld):
	source = [
		'basefilesystem.cpp',
		'basefilesystemasync.cpp',
		'filetracker.cpp',
		'filesystemasync.cpp',
		'filesystem_stdio.cpp',
		'../public/kevvaluescompiler.cpp',
		'../public/zip_utils.cpp',
		'QueuedLoader.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS != 'win32': # POSIX
		source += [
			'linux_support.cpp'
		]

	bld.shlib(
		target = 'filesystem_stdio',
		features = 'cxx',
		source = source,
		use = 'tier0 tier1 tier2 interfaces vstdlib vpklib',
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
