#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('BT_THREADSAFE',1)

def build(bld):
	SRCS = [
		'btAlignedAllocator.cpp',
		'btConvexHull.cpp',
		'btConvexHullComputer.cpp',
		'btGeometryUtil.cpp',
		'btPolarDecomposition.cpp',
		'btQuickprof.cpp',
		'btReducedVector.cpp',
		'btSerializer.cpp',
		'btSerializer64.cpp',
		'btThreads.cpp',
		'btVector3.cpp',
		'TaskScheduler/btTaskScheduler.cpp',
		'TaskScheduler/btThreadSupportPosix.cpp',
		'TaskScheduler/btThreadSupportWin32.cpp'
	]

	INCS = [
		'..'
	]

	bld.stlib(target = 'LinearMath',
		features = 'cxx',
		source = SRCS,
		includes = INCS,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM)
