#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	SRCS = [
		'tier3.cpp',
		'mdlutils.cpp',
		'choreoutils.cpp',
		'scenetokenprocessor.cpp',
		'studiohdrstub.cpp'
	]

	bld.stlib(target = 'tier3',
		features = 'cxx',
		source = SRCS,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM)
