#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	PROJECT = 'tier3'

	SRCS = [
		'tier3.cpp',
		'mdlutils.cpp',
		'choreoutils.cpp',
		'scenetokenprocessor.cpp',
		'studiohdrstub.cpp'
	]

	bld.stlib(target = PROJECT,
		features = 'cxx',
		source = SRCS,
		install_path = bld.env.LIBDIR,
		idx = PROJECT,
		subsystem = bld.env.MSVC_SUBSYSTEM)
