#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	source = [
		'gcclient.cpp',
		'gcconstants.cpp',
		'gclogger.cpp',
		'gcmsg.cpp',
		'job.cpp',
		'jobmgr.cpp',
		'jobtime.cpp',
		'messagelist.cpp',
		'msgprotobuf.cpp',
		'netpacket.cpp',
		'netpacketpool.cpp',
		'protobufsharedobject.cpp',
		'sharedobject.cpp',
		'sharedobjectcache.cpp',
		'gcclient_sharedobjectcache.cpp',
		'steamextra/misc.cpp',
		'steamextra/rtime.cpp',
		'steamextra/steamid.cpp',
		'steamextra/tier1/hashglobals.cpp',
		'steamextra/tier1/tsmempool.cpp',
		'steamextra/tier1/tsmultimempool.cpp',
		'workthreadpool.cpp',
		'webapi_response.cpp',
		'../thirdparty/JSON_parser/JSON_parser.c'
	]

	bld.stlib(
		target = 'gcsdk',
		features = 'cxx',
		source = source,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
