#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('LAUNCHERONLY',1)

def build(bld):
	source = [
		'../public/filesystem_init.cpp',
		'launcher.cpp',
		'reslistgenerator.cpp',
		'../public/tier0/memoverride.cpp'
	]

	bld.shlib(
		target = 'launcher',
		features = 'cxx',
		source = source,
		use = 'tier0 tier1 tier2 tier3 interfaces vstdlib appframework togl SDL2',
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
