#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	source = [
		'FakeSteamAPI_ContextProvider.cpp',
		'FakeSteamAPI_Core.cpp',
		'FakeSteamAPI_LogSys.cpp',
		'FakeSteamAPI_Settings.cpp',
		'FakeSteamAPI_Utilities.cpp',
		'../public/tier0/memoverride.cpp'
	]

	bld.shlib(
		target = 'steam_api',
		features = 'cxx',
		source = source,
		use = 'tier0',
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
