#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('TOGL_DLL_EXPORT',1)

def build(bld):
	source = [
		'dx9asmtogl2.cpp',
		'dxabstract.cpp',
		'glentrypoints.cpp',
		'glmgr.cpp',
		'glmgrbasics.cpp',
		'cglmtex.cpp',
		'cglmfbo.cpp',
		'cglmprogram.cpp',
		'cglmbuffer.cpp',
		'cglmquery.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'darwin':
		source += [
			'glmgrcocoa.mm',
			'intelglmallocworkaround.cpp',
			'mach_override.c'
		]

	bld.shlib(
		target = 'togl',
		features = 'cxx',
		source = source,
		use = 'tier0 tier1 tier2 interfaces vstdlib mathlib appframework SDL2',
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
