#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('TOGL_DLL_EXPORT',1)

def build(bld):
	PROJECT = 'togl'

	SRCS = [
		'dx9asmtogl2.cpp',
		'dxabstract.cpp',
		'glentrypoints.cpp',	
		'glmgr.cpp',			
		'glmgrbasics.cpp',	
		'cglmtex.cpp',		
		'cglmfbo.cpp',		
		'cglmprogram.cpp',	
		'cglmbuffer.cpp',	
		'cglmquery.cpp',
		'../public/tier0/memoverride.cpp'
	]

	LIBS = [
		'tier0',
		'tier1',
		'tier2',
		'interfaces',
		'vstdlib',
		'mathlib',
		'appframework',
		'SDL2'
	]

	bld.shlib(target = PROJECT,
		features = 'cxx',
		source = SRCS,
		use = LIBS,
		install_path = bld.env.LIBDIR,
		idx = PROJECT,
		subsystem = bld.env.MSVC_SUBSYSTEM)
