#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('mathlib', 1)

def build(bld):
	source = [
		'expressioncalculator.cpp',
		'color_conversion.cpp',
		'cholesky.cpp',
		'halton.cpp',
		'lightdesc.cpp',
		'mathlib_base.cpp',
		'powsse.cpp',
		'sparse_convolution_noise.cpp',
		'sseconst.cpp',
		'sse.cpp',
		'ssenoise.cpp',
		'anorms.cpp',
		'bumpvects.cpp',
		'IceKey.cpp',
		'kdop.cpp',
		'imagequant.cpp',
		'spherical.cpp',
		'polyhedron.cpp',
		'quantize.cpp',
		'randsse.cpp',
		'simdvectormatrix.cpp',
		'vmatrix.cpp',
		'almostequal.cpp',
		'simplex.cpp',
		'eigen.cpp',
		'camera.cpp',
		'planefit.cpp',
		'polygon.cpp',
		'volumeculler.cpp',
		'transform.cpp',
		'sphere.cpp',
		'capsule.cpp'
	]

	if bld.env.DEST_OS != 'darwin':
		source += [
			'box_buoyancy.cpp'
		]

	bld.stlib(
		target = 'mathlib',
		features = 'cxx',
		includes = '../public/mathlib',
		source = source,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
