#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('BT_THREADSAFE',1)

def build(bld):
	PROJECT = 'BulletCollision'

	SRCS = bld.path.ant_glob([
		'**/*.cpp'
	])

	INCS = [
		'..'
	]

	bld.stlib(target = PROJECT,
		features = 'cxx',
		source = SRCS,
		includes = INCS,
		install_path = bld.env.LIBDIR,
		idx = PROJECT,
		subsystem = bld.env.MSVC_SUBSYSTEM)
