#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	source = [
		'AppSystemGroup.cpp',
		'../public/filesystem_init.cpp'
	]

	if bld.env.DEST_OS in ['linux','android']:
		source += [
			'sdlmgr.cpp'
		]

	if bld.env.DEST_OS == 'darwin':
		source += [
			'cocoamgr.mm'
		]

	if bld.env.DEST_OS == 'win32':
		source += [
			'VguiMatSysApp.cpp',
			'matsysapp.cpp',
			'WinApp.cpp'
		]
	else: # POSIX
		source += [
			'posixapp.cpp'
		]

	bld.stlib(
		target = 'appframework',
		features = 'cxx',
		source = source,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
