#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	PROJECT = 'appframework'

	SRCS = [
		'AppSystemGroup.cpp',
		'../public/filesystem_init.cpp'
	]

	if bld.env.DEST_OS != 'win32':
		SRCS += [
			'posixapp.cpp'
		]

	if bld.env.DEST_OS in ['linux','android']:
		SRCS += [
			'sdlmgr.cpp'
		]

	bld.stlib(target = PROJECT,
		features = 'cxx',
		source = SRCS,
		idx = PROJECT,
		subsystem = bld.env.MSVC_SUBSYSTEM)
