#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld.stlib(
		target = 'vaudio_miles', # replace vaudio_miles
		features = 'cxx',
		source = 'vaudio_minimp3.cpp',
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
