#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('TIER0_DLL_EXPORT', 1)
	conf.define('CROSS_PLATFORM_VERSION', 1)
	conf.define_cond('THREAD_MUTEX_TRACING_ENABLED', conf.env.DEST_OS == 'win32')

def build(bld):
	source = [
		'../unitlib/unitlib.cpp',
		'assert_dialog.cpp',
		'commandline.cpp',
		'cpu.cpp',
		'cpumonitoring.cpp',
		'cputopology.cpp',
		'dbg.cpp',
		'fasttimer.cpp',
		'logging.cpp',
		'mem.cpp',
		'mem_helpers.cpp',
		'memdbg.cpp',
		'memvirt.cpp',
		'memstd.cpp',
		'memvalidate.cpp',
		'dynfunction.cpp',
		'minidump.cpp',
		'tier0_strtools.cpp',			
		'miniprofiler.cpp',			
		'perfstats.cpp',
		'platform_independent.cpp',
		'platwindow.cpp',
		'progressbar.cpp',
		'security.cpp',
		'stackstats.cpp',
		'stacktools.cpp',
		'systeminformation.cpp',
		'threadtools.cpp',
		'tslist.cpp',
		'vatoms.cpp',
		'vprof.cpp',
		'vtuneinterface.cpp',
		'win32consoleio.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'assert_dialog.rc',
			'etwprof.cpp',
			'memprocessheap.cpp',
			'platform.cpp',
			'pme.cpp',
			'PMELib.cpp',
			'dlmalloc/malloc.cpp'
		]
	else: # POSIX
		source += [
			'cpu_posix.cpp',
			'platform_posix.cpp',
			'pme_posix.cpp'
		]

	bld.shlib(
		target = 'tier0',
		features = 'cxx',
		source = source,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
