#! /usr/bin/env python

from waflib import Logs
import os
import sys

top = '.'

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	source = [
		'main.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += ['launcher_main.rc']

	bld(source = source,
		target = 'csgo',
		features = 'c cxx cxxprogram',
		use = 'dl',
		install_path = bld.env.BINDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
