#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('VSTDLIB_DLL_EXPORT',1)

def build(bld):
	PROJECT = 'vstdlib'

	SRCS = [
		'coroutine.cpp',
		'cvar.cpp',
		'jobthread.cpp',
		'keyvaluessystem.cpp',
		'random.cpp',
		'vcover.cpp',
		'eventsystem.cpp',
		'vstrtools.cpp',
		'vstdlib_strtools.cpp',
		'../public/tier0/memoverride.cpp'
	]

	LIBS = [
		'tier0',
		'tier1',
		'interfaces'
	]

	bld.shlib(target = PROJECT,
		features = 'cxx',
		source = SRCS,
		use = LIBS,
		install_path = bld.env.LIBDIR,
		idx = PROJECT,
		subsystem = bld.env.MSVC_SUBSYSTEM)
