#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('VSTDLIB_DLL_EXPORT', 1)

def build(bld):
	source = [
		'coroutine.cpp',
		'cvar.cpp',
		'jobthread.cpp',
		'keyvaluessystem.cpp',
		'random.cpp',
		'vcover.cpp',
		'eventsystem.cpp',
		'vstrtools.cpp',
		'vstdlib_strtools.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'getstackptr64.masm',
			'processutils.cpp'
		]

	bld.shlib(
		target = 'vstdlib',
		features = 'cxx',
		source = source,
		use = 'tier0 tier1 interfaces',
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
