#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld.stlib(
		target = 'interfaces',
		features = 'cxx',
		source = 'interfaces.cpp',
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
