#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	SRCS = [
		'interfaces.cpp'
	]

	bld.stlib(target = 'interfaces',
		features = 'cxx',
		source = SRCS,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM)
