#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	PROJECT = 'interfaces'

	SRCS = [
		'interfaces.cpp'
	]

	bld.stlib(target = PROJECT,
		features = 'cxx',
		source = SRCS,
		idx = PROJECT,
		subsystem = bld.env.MSVC_SUBSYSTEM)
