#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('BT_THREADSAFE',1)

def build(bld):
	PROJECT = 'BulletSoftBody'

	SRCS = [
		'btSoftBody.cpp',
		'btSoftBodyConcaveCollisionAlgorithm.cpp',
		'btSoftBodyHelpers.cpp',
		'btSoftBodyRigidBodyCollisionConfiguration.cpp',
		'btSoftRigidCollisionAlgorithm.cpp',
		'btSoftRigidDynamicsWorld.cpp',
		'btSoftMultiBodyDynamicsWorld.cpp',
		'btSoftSoftCollisionAlgorithm.cpp',
		'btDefaultSoftBodySolver.cpp',
		'btDeformableBackwardEulerObjective.cpp',
		'btDeformableBodySolver.cpp',
		'btDeformableMultiBodyConstraintSolver.cpp',
		'btDeformableContactProjection.cpp',
		'btDeformableMultiBodyDynamicsWorld.cpp',
		'btDeformableContactConstraint.cpp',
		'poly34.cpp',
		'BulletReducedDeformableBody/btReducedDeformableBody.cpp',
		'BulletReducedDeformableBody/btReducedDeformableBodyHelpers.cpp',
		'BulletReducedDeformableBody/btReducedDeformableBodySolver.cpp',
		'BulletReducedDeformableBody/btReducedDeformableContactConstraint.cpp'
	]

	INCS = [
		'..'
	]

	bld.stlib(target = PROJECT,
		features = 'cxx',
		source = SRCS,
		includes = INCS,
		install_path = bld.env.LIBDIR,
		idx = PROJECT,
		subsystem = bld.env.MSVC_SUBSYSTEM)
