#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('BT_THREADSAFE',1)

def build(bld):
	PROJECT = 'vphysics'

	SRCS = bld.path.ant_glob('*.cpp') + ['../public/tier0/memoverride.cpp']

	INCS = [
		'../bullet'
	]

	LIBS = [
		'tier0',
		'tier1',
		'tier2',
		'tier3',
		'interfaces',
		'vstdlib',
		'mathlib',
		'BulletSoftBody',
		'BulletDynamics',
		'BulletCollision',
		'LinearMath'
	]


	bld.shlib(target = PROJECT,
		features = 'cxx',
		source = SRCS,
		includes = INCS,
		use = LIBS,
		install_path = bld.env.LIBDIR,
		idx = PROJECT,
		subsystem = bld.env.MSVC_SUBSYSTEM)
