#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	conf.define('JPH_DISABLE_CUSTOM_ALLOCATOR', 1)
	conf.define('JPH_DEBUG_RENDERER',1)

def build(bld):
	source = [
		'cbase.cpp',
		'../public/collisionutils.cpp',
		'../public/filesystem_helpers.cpp',
		'vjolt_collide.cpp',
		'vjolt_collide_trace.cpp',
		'vjolt_constraints.cpp',
		'vjolt_controller_fluid.cpp',
		'vjolt_controller_motion.cpp',
		'vjolt_controller_player.cpp',
		'vjolt_controller_vehicle.cpp',
		'vjolt_controller_shadow.cpp',
		'vjolt_debugrender.cpp',
		'vjolt_environment.cpp',
		'vjolt_friction.cpp',
		'vjolt_interface.cpp',
		'vjolt_keyvalues_schema.cpp',
		'vjolt_object.cpp',
		'vjolt_objectpairhash.cpp',
		'vjolt_parse.cpp',
		'vjolt_querymodel.cpp',
		'vjolt_surfaceprops.cpp',
		'../public/tier0/memoverride.cpp'
	]

	bld.shlib(
		target = 'vphysics',
		features = 'cxx',
		includes = '../thirdparty/joltphysics',
		source = source,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
