#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	SRCS = [
		'beamsegdraw.cpp',
		'defaultfilesystem.cpp',
		'fileutils.cpp',
		'keybindings.cpp',
		'../public/map_utils.cpp',
		'../public/materialsystem/MaterialSystemUtil.cpp',
		'meshutils.cpp',
		'p4helpers.cpp',
		'renderutils.cpp',
		'riff.cpp',
		'soundutils.cpp',
		'tier2.cpp',
		'tier2_logging.cpp',
		'tokenreader.cpp',
		'util_init.cpp',
		'utlstreambuffer.cpp',
		'vconfig.cpp',
		'schemaclassbinding.cpp',
		'socketcreator.cpp',
		'resourceprecacher.cpp',
		'interval.cpp'
	]

	INCS = [
		'../public/tier2'
	]

	bld.stlib(target = 'tier2',
		features = 'cxx',
		source = SRCS,
		includes = INCS,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM)
