#!/usr/bin/env python

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):

	bld.stlib(
		target = 'vpklib',
		features = 'cxx',
		source = 'packedstore.cpp',
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
